env:
    browser: true
    es6: true
root: true
extends:
    - 'eslint:recommended'
    - 'plugin:react/recommended'
    - 'plugin:@typescript-eslint/eslint-recommended'
    - 'plugin:@typescript-eslint/recommended'
globals:
    Atomics: readonly
    SharedArrayBuffer: readonly
parser: '@typescript-eslint/parser'
parserOptions:
    ecmaFeatures:
        jsx: true
    ecmaVersion: 2020
    sourceType: module
plugins:
    - react
    - '@typescript-eslint'
rules:
    indent:
        - error
        - tab
    linebreak-style:
        - error
        - unix
    quotes:
        - error
        - single
    semi:
        - error
        - always
    '@typescript-eslint/explicit-function-return-type': off
    '@typescript-eslint/no-unused-vars': off
    'react/jsx-filename-extension':
        - 1
        - extensions:
            - ".js"
            - ".jsx"
            - ".ts"
            - ".tsx"
